const archer = {
	abilities: [ // indentation funky so it's easier to fit on screen
{name: "Arrow Bomb",				img: "archer",	linked: [1],						depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Bow Proficiency 1",			img: "white",	linked: [0, 2, 3],					depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper Arrow Bomb",		img: "white",	linked: [1],						depend: 0,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Heart Shatter",				img: "yellow",	linked: [1, 4],						depend: 0,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Escape",					img: "archer",	linked: [3, 5, 6],					depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Double Shots",				img: "white",	linked: [4, 7],						depend: null,	blockedBy: [6],				archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "Power Shots",				img: "white",	linked: [4, 8],						depend: null,	blockedBy: [5],				archetype: "Sharpshooter",	cost: 1, archReq: 0},
{name: "Arrow Storm",				img: "archer",	linked: [5, 9, 10, 11, 12],			depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Arrow Shield",				img: "archer",	linked: [6, 9, 14, 15],				depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper Escape",			img: "white",	linked: [7, 8, 12, 13, 14],			depend: 4,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Windy Feet",				img: "yellow",	linked: [7, 11],					depend: 4,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Air Mastery",				img: "white",	linked: [7, 10, 16],				depend: null,	blockedBy: null,			archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "Thunder Mastery",			img: "white",	linked: [7, 9, 13, 14, 17],			depend: null,	blockedBy: null,			archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "Water Mastery",				img: "white",	linked: [9, 12, 14, 20],			depend: null,	blockedBy: null,			archetype: "Sharpshooter",	cost: 1, archReq: 0},
{name: "Fire Mastery",				img: "white",	linked: [8, 9, 12, 13, 21],			depend: null,	blockedBy: null,			archetype: "Sharpshooter",	cost: 1, archReq: 0},
{name: "Earth Mastery",				img: "white",	linked: [8, 22],					depend: null,	blockedBy: null,			archetype: "Trapper",		cost: 1, archReq: 0},
{name: "Arrow Rain",				img: "yellow",	linked: [11, 17, 18],				depend: 8,		blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "Nimble String",				img: "yellow",	linked: [12, 16, 19],				depend: 7,		blockedBy: [20],			archetype: null,			cost: 2, archReq: 0},
{name: "Triple Shots",				img: "white",	linked: [16, 19, 23],				depend: 5,		blockedBy: null,			archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "Frenzy",					img: "yellow",	linked: [17, 18, 23],				depend: null,	blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 0},
{name: "Phantom Ray",				img: "pink",	linked: [13, 21, 24],				depend: 7,		blockedBy: [17, 26, 53],	archetype: null,			cost: 2, archReq: 0},
{name: "Fire Creep",				img: "yellow",	linked: [14, 20, 22],				depend: 0,		blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "Bryophyte Roots",			img: "yellow",	linked: [15, 21, 25],				depend: 7,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 1},
{name: "Guardian Angels",			img: "red",		linked: [18, 19, 26],				depend: 8,		blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 3},
{name: "Focus",						img: "red",		linked: [20, 27, 28],				depend: null,	blockedBy: null,			archetype: "Sharpshooter",	cost: 2, archReq: 2},
{name: "Basaltic Trap",				img: "red",		linked: [22, 29],					depend: 0,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 2},
{name: "Windstorm",					img: "yellow",	linked: [23, 27, 30, 34],			depend: 7,		blockedBy: [20],			archetype: null,			cost: 2, archReq: 0},
{name: "Cheaper Arrow Storm",		img: "white",	linked: [24, 26, 28, 31],			depend: 7,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Grappling Hook",			img: "pink",	linked: [24, 27, 29, 31, 32],		depend: 4,		blockedBy: [47],			archetype: "Trapper",		cost: 2, archReq: 0},
{name: "More Shields",				img: "white",	linked: [25, 28, 32, 33],			depend: 8,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Stormy Feet",				img: "white",	linked: [26],						depend: 10,		blockedBy: null,			archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "More Focus",				img: "white",	linked: [27, 28, 37],				depend: 24,		blockedBy: null,			archetype: "Sharpshooter",	cost: 1, archReq: 0},
{name: "Implosion",					img: "yellow",	linked: [28, 29],					depend: 25,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 0},
{name: "Patient Hunter",			img: "yellow",	linked: [29],						depend: 25,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 0},
{name: "Refined Gunpowder",			img: "white",	linked: [26, 35, 36, 41],			depend: 0,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Traveler",					img: "white",	linked: [34, 36, 37],				depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Fierce Stomp",				img: "yellow",	linked: [34, 35],					depend: 4,		blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 0},
{name: "Twain's Arc",				img: "pink",	linked: [31, 35, 38, 44, 45],		depend: 24,		blockedBy: null,			archetype: "Sharpshooter",	cost: 2, archReq: 4},
{name: "Scorched Earth",			img: "yellow",	linked: [37, 44],					depend: 21,		blockedBy: null,			archetype: "Sharpshooter",	cost: 1, archReq: 0},
{name: "Bouncing Bomb",				img: "pink",	linked: [29, 40],					depend: 0,		blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "More Traps",				img: "white",	linked: [39, 46],					depend: 25,		blockedBy: null,			archetype: "Trapper",		cost: 1, archReq: 0},
{name: "Leap",						img: "yellow",	linked: [34, 42, 43, 47],			depend: null,	blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 5},
{name: "Better Leap",				img: "white",	linked: [41, 43],					depend: 41,		blockedBy: null,			archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "Homing Shots",				img: "pink",	linked: [41, 42, 44, 48],			depend: null,	blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "Shocking Bomb",				img: "yellow",	linked: [37, 43, 45, 49],			depend: 0,		blockedBy: null,			archetype: "Sharpshooter",	cost: 2, archReq: 5},
{name: "Better Arrow Shield",		img: "white",	linked: [37, 38, 44, 46, 49],		depend: 8,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Mana Trap",					img: "red",		linked: [40, 45, 52],				depend: 25,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 5},
{name: "Escape Artist",				img: "yellow",	linked: [41, 48, 43],				depend: 4,		blockedBy: [28],			archetype: null,			cost: 2, archReq: 0},
{name: "Better Guardian Angels",	img: "white",	linked: [43, 47, 55],				depend: 23,		blockedBy: null,			archetype: "Boltslinger",	cost: 1, archReq: 0},
{name: "Initiator",					img: "pink",	linked: [44, 45, 50, 51, 52, 56],	depend: 24,		blockedBy: null,			archetype: "Sharpshooter",	cost: 2, archReq: 5},
{name: "Rocket Jump",				img: "white",	linked: [49, 51, 52],				depend: 0,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Call of the Hound",			img: "pink",	linked: [49, 50, 52, 58],			depend: 8,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 0},
{name: "Cheaper Arrow Storm",		img: "white",	linked: [46, 49, 50, 51],			depend: 7,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Arrow Hurricane",			img: "red",		linked: [47, 54, 55],				depend: 7,		blockedBy: [20],			archetype: "Boltslinger",	cost: 2, archReq: 8},
{name: "Shrapnel Bomb",				img: "yellow",	linked: [53, 55, 60],				depend: 0,		blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 8},
{name: "Precise Shot",				img: "white",	linked: [48, 53, 54, 56],			depend: null,	blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper Arrow Shield",		img: "white",	linked: [49, 55, 57, 62],			depend: 8,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Decimator",					img: "yellow",	linked: [56, 58], 					depend: 20,		blockedBy: null,			archetype: "Sharpshooter",	cost: 2, archReq: 0},
{name: "Cheaper Escape",			img: "white",	linked: [51, 57, 59, 67],			depend: 4,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Stronger Hook",				img: "white",	linked: [58],						depend: 28,		blockedBy: null,			archetype: "Trapper",		cost: 1, archReq: 5},
{name: "Geyser Stomp",				img: "yellow",	linked: [54, 61, 63],				depend: 36,		blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "Elusive",					img: "yellow",	linked: [60],						depend: 7,		blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 0},
{name: "Crepuscular Ray",			img: "red",		linked: [56, 65],					depend: 7,		blockedBy: null,			archetype: "Sharpshooter",	cost: 2, archReq: 10},
{name: "Snow Storm",				img: "pink",	linked: [60, 64, 65],				depend: null,	blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "All-Seeing Panoptes",		img: "red",		linked: [63],						depend: 23,		blockedBy: null,			archetype: "Boltslinger",	cost: 2, archReq: 11},
{name: "More Focus",				img: "white",	linked: [62, 63, 66],				depend: 24,		blockedBy: null,			archetype: "Sharpshooter",	cost: 1, archReq: 0},
{name: "Cheaper Arrow Bomb",		img: "white",	linked: [65, 70],					depend: 0,		blockedBy: null,			archetype: null,			cost: 1, archReq: 0},
{name: "Grape Bomb",				img: "pink",	linked: [58, 68, 69, 70],			depend: 0,		blockedBy: null,			archetype: null,			cost: 2, archReq: 0},
{name: "Tangled Traps",				img: "yellow",	linked: [67],						depend: 25,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 0},
{name: "Stronger Patient Hunter",	img: "white",	linked: [67],						depend: 33,		blockedBy: null,			archetype: "Trapper",		cost: 1, archReq: 0},
{name: "Minefield",					img: "red",		linked: [66, 67],					depend: 25,		blockedBy: null,			archetype: "Trapper",		cost: 2, archReq: 10}
	],
	tree: [ // indentation funky so it's easier to fit on screen
[null,							null,							null,						null,								0,									null,								null,								null,							null],
[null,							null,							null,						null,								[[0], null, [1], null],				null,								null,								null,							null],
[null,							null,							null,						null,								1,									[null, [1], null, [2]],				2,									null,							null],
[null,							null,							null,						null,								[[1], null, [3], null],				null,								null,								null,							null],
[null,							null,							null,						null,								3,									null,								null,								null,							null],
[null,							null,							null,						null,								[[3], null, [4], null],				null,								null,								null,							null],
[null,							null,							5,							[null, [5], null, [4]],				4,									[null, [4], null, [6]],				6,									null,							null],
[null,							null,							[[5], null, [7], null],		null,								null,								null,								[[6], null, [8], null],				null,							null],
[[null, null, [11], [7, 10]],	[null, [11], [10], [7]],		7,							[null, [7], null, [9]],				9,									[null, [9], null, [8]],				8,									[null, [8], null, [15]],		[null, [8], [15], null]],
[[[7, 10], null, [11], null],	10,								[[7], null, [12], null],	null,								[[9], null, [12, 13, 14], null],	null,								[[8], null, [14], null],			null,							[[8], null, [15], null]],
[[[7, 10], null, [11], null],	null,							[[7], null, [12], null],	null,								[[9], null, [12, 13, 14], null],	null,								[[8], null, [14], null],			null,							[[8], null, [15], null]],
[11,							null,							12,							[null, [12], null, [9, 13, 14]],	[[9], [12], [13], [14]],			[null, [9, 12, 13], null, [14]],	14,									null,							15],
[[[11], null, [16], null],		null,							[[12], null, [17], null],	null,								13,									null,								[[14], null, [21], null],			null,							[[15], null, [22], null]],
[16,							[null, [16], null, [17]],		17,							null,								[[13], null, [20], null],			null,								[[14], null, [21], null],			null,							[[15], null, [22], null]],
[[[16], null, [18], null],		null,							[[17], null, [19], null],	null,								20,									[null, [20], null, [21]],			21,									[null, [21], null, [22]],		22],
[18,							[null, [18], [23], [19]],		19,							null,								[[20], null, [24], null],			null,								null,								null,							[[22], null, [25], null]],
[null,							[[18, 19], null, [23], null],	null,						null,								[[20], null, [24], null],			null,								null,								null,							[[22], null, [25], null]],
[null,							23,								null,						[null, null, [27], [24]],			24,									[null, [24], [28], null],			null,								[null, null, [29], [25]],		25],
[null,							[[23], null, [26], null],		null,						[[24], null, [27], null],			null,								[[24], null, [28], null],			null,								[[25], null, [29], null],		null],
[null,							26,								[null, [26], null, [27]],	27,									[null, [27], [31], [28]],			28,									[null, [28], [32], [29]],			29,								[null, [29], [33], null]],
[null,							[[26], null, [30], null],		null,						null,								31,									null,								32,									[[29], null, [39], null],		33],
[[null, null, [34], [30]],		30,								null,						null,								[[31], null, [37], null],			null,								null,								[[29], null, [39], null],		null],
[[[30], null, [34], null],		null,							null,						null,								[[31], null, [37], null],			null,								null,								[[29], null, [39], null],		null],
[34,							[null, [34], [36], [35]],		35,							[null, [35], null, [37]],			37,									[null, [37], [38], [45]],			[null, [37, 38], [45], null],		39,								[null, [39], [40], null]],
[[[34], null, [41], null],		36,								null,						null,								null,								38,									[[37, 38], null, [45], null],		null,							40],
[[[34], null, [41], null],		null,							null,						null,								null,								null,								[[37, 38], null, [45], null],		null,							[[40], null, [46], null]],
[41,							[null, [41], [42], [43]],		43,							[null, [43], null, [44]],			44,									[null, [44], [49], [45]],			45,									[null, [45], null, [46]],		46],
[[[41], null, [47], null],		42,								[[43], null, [48], null],	null,								null,								[[44, 45], null, [49], null],		null,								null,							[[46], null, [52], null]],
[[[41], null, [47], null],		null,							[[43], null, [48], null],	null,								null,								[[44, 45], null, [49], null],		null,								null,							[[46], null, [52], null]],
[47,							[null, [47], null, [48]],		48,							null,								[null, null, [56], [49]],			49,									[null, [49], [50], [51, 52]],		[null, [49, 50], [51], [52]],	52],
[[[47], null, [53], null],		null,							[[48], null, [55], null],	null,								[[49], null, [56], null],			null,								[[49, 51, 52], null, [50], null],	51,								null],
[53,							[null, [53], [54], [55]],		55,							[null, [55], null, [56]],			56,									[null, [56], [57], null],			50,									[[51], null, [58], null],		null],
[null,							54,								null,						null,								[[56], null, [62], null],			57,									[null, [57], null, [58]],			58,								[null, [58], [59], null]],
[null,							[[54], null, [60], null],		null,						null,								[[56], null, [62], null],			null,								null,								[[58], null, [67], null],		59],
[null,							[[54], null, [60], null],		null,						null,								[[56], null, [62], null],			null,								null,								[[58], null, [67], null],		null],
[[null, null, [61], [64]],		60,								[null, [60], [63], null],	null,								62,									null,								[null, null, [68], [67]],			67,								[null, [67], [69], null]],
[61,							null,							[[60], null, [63], null],	null,								[[62], null, [65], null],			null,								68,									[[67], null, [70], null],		69],
[null,							[null, null, [64], [63]],		63,							[null, [63], null, [65]],			65,									[null, [65], [66], null],			null,								[[67], null, [70], null],		null],
[null,							64,								null,						null,								null,								66,									[null, [66], null, [70]],			70,								null]
	],
	pages: [5, 10, 16, 22, 28, 34],
	archetypes: {"Boltslinger": {color: "#ffff55", icon: "2"}, "Sharpshooter": {color: "#ff55ff", icon: "6"}, "Trapper": {color: "#00aa00", icon: "5"}},
	chosen: [0],
	descriptions: [ // indentation funky so it's easier to fit on screen
	]
}