const warrior = {
	abilities: [ // indentation funky so it's easier to fit on screen
{name: "Bash",						img: "warrior",	linked: [1],						depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Spear Proficiency 1",		img: "white",	linked: [0, 2, 3],					depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper Bash",				img: "white",	linked: [1],						depend: 0,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Double Bash",				img: "yellow",	linked: [1, 4],						depend: 0,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Charge",					img: "warrior",	linked: [3, 6, 10],					depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Vehement",					img: "white",	linked: [10, 7],					depend: null,	blockedBy: [6],		archetype: "Fallen",		cost: 1, archReq: 0},
{name: "Tougher Skin",				img: "white",	linked: [4, 8],						depend: null,	blockedBy: [5],		archetype: "Paladin",		cost: 1, archReq: 0},
{name: "Uppercut",					img: "warrior",	linked: [5, 9, 11, 12],				depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "War Scream",				img: "warrior",	linked: [6, 9, 13, 14],				depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper Charge",			img: "white",	linked: [7, 8, 12, 13, 15],			depend: 4,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Heavy Impact",				img: "yellow",	linked: [4, 5],						depend: 4,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Earth Mastery",				img: "white",	linked: [7, 16],					depend: null,	blockedBy: null,	archetype: "Fallen",		cost: 1, archReq: 0},
{name: "Thunder Mastery",			img: "white",	linked: [7, 9, 13, 15, 17],			depend: null,	blockedBy: null,	archetype: "Fallen",		cost: 1, archReq: 0},
{name: "Air Mastery",				img: "white",	linked: [8, 9, 12, 15, 18],			depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 1, archReq: 0},
{name: "Fire Mastery",				img: "white",	linked: [8, 19],					depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 1, archReq: 0},
{name: "Water Mastery",				img: "white",	linked: [9, 12, 13, 20],			depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 1, archReq: 0},
{name: "Quadruple Bash",			img: "yellow",	linked: [11, 17, 25],				depend: 0,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0},
{name: "Fireworks",					img: "yellow",	linked: [12, 16, 25],				depend: 7,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0},
{name: "Flyby Jab",					img: "yellow",	linked: [13, 19, 21],				depend: 4,		blockedBy: null,	archetype: null,			cost: 2, archReq: 0},
{name: "Flaming Uppercut",			img: "yellow",	linked: [14, 18, 21],				depend: 7,		blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 0},
{name: "Half-Moon Swipe",			img: "yellow",	linked: [15, 22],					depend: 7,		blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 1},
{name: "Iron Lungs",				img: "white",	linked: [18, 19, 24],				depend: 8,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Counter",					img: "yellow",	linked: [20, 23, 27],				depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 0},
{name: "Generalist",				img: "red",		linked: [22, 27],					depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 3},
{name: "Mantle of the Bovemists",	img: "red",		linked: [21, 29],					depend: 8,		blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 3},
{name: "Bak'al's Grasp",			img: "red",		linked: [16, 17, 26],				depend: 8,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 2},
{name: "Spear Proficiency 2",		img: "white",	linked: [25, 27, 30, 32],			depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper Uppercut",			img: "white",	linked: [22, 23, 26, 28, 30, 35],	depend: 7,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Aerodynamics",				img: "yellow",	linked: [27, 29, 31],				depend: 4,		blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 0},
{name: "Provoke",					img: "yellow",	linked: [24, 28, 31, 33],			depend: 8,		blockedBy: null,	archetype: "Paladin",		cost: 1, archReq: 0},
{name: "Precise Strikes",			img: "white",	linked: [26, 27],					depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Air Shout",					img: "yellow",	linked: [28, 29],					depend: 8,		blockedBy: null,	archetype: null,			cost: 2, archReq: 0},
{name: "Enraged Blow",				img: "pink",	linked: [26, 36],					depend: 25,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0},
{name: "Manachism",					img: "pink",	linked: [29, 34, 40],				depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 3},
{name: "Stronger Mantle",			img: "white",	linked: [33, 35, 38],				depend: 24,		blockedBy: null,	archetype: "Paladin",		cost: 1, archReq: 0},
{name: "Flying Kick",				img: "yellow",	linked: [27, 34, 37, 38],			depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 1},
{name: "Boiling Blood",				img: "yellow",	linked: [32, 37, 41, 45],			depend: 0,		blockedBy: null,	archetype: null,			cost: 2, archReq: 0},
{name: "Ragnarokkr",				img: "pink",	linked: [35, 36, 41, 42],			depend: 8,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0},
{name: "Ambidextrous",				img: "white",	linked: [34, 35, 39, 43, 47],		depend: 22,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Burning Heart",				img: "white",	linked: [38, 40, 43, 44],			depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 1, archReq: 0},
{name: "Stronger Bash",				img: "white",	linked: [33, 39, 44],				depend: null,	blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Intoxicating Blood",		img: "yellow",	linked: [36, 37],					depend: 25,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 5},
{name: "Comet",						img: "yellow",	linked: [37],						depend: 17,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0},
{name: "Collide",					img: "yellow",	linked: [38, 39],					depend: 35,		blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 4},
{name: "Rejuvenating Skin",			img: "red",		linked: [39, 40, 48],				depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 5},
{name: "Uncontainable Corruption",	img: "white",	linked: [36, 46, 51, 68],			depend: 25,		blockedBy: null,	archetype: "Fallen",		cost: 1, archReq: 0},
{name: "Radiant Devotee",			img: "white",	linked: [45, 47, 68],				depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 1, archReq: 1},
{name: "Whirlwind Strike",			img: "yellow",	linked: [38, 46, 53],				depend: 7,		blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 5},
{name: "Mithril Skin",				img: "yellow",	linked: [44, 49, 50],				depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 6},
{name: "Shield Strike",				img: "yellow",	linked: [48, 50, 57],				depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 0},
{name: "Sparking Hope",				img: "pink",	linked: [48, 49, 57],				depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 0},
{name: "Massive Bash",				img: "pink",	linked: [45, 52, 54, 58],			depend: 0,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 8},
{name: "Tempest",					img: "yellow",	linked: [51, 53, 54, 55],			depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 0},
{name: "Spirit of the Rabbit",		img: "white",	linked: [47, 52, 55, 56],			depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 1, archReq: 5},
{name: "Massacre",					img: "yellow",	linked: [51, 52],					depend: null,	blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 5},
{name: "Axe Kick",					img: "white",	linked: [52, 53],					depend: 7,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Radiance",					img: "pink",	linked: [53, 57],					depend: 0,		blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 2},
{name: "Cheaper Bash",				img: "white",	linked: [49, 50, 56, 61],			depend: 0,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Cheaper War Scream",		img: "white",	linked: [51, 63],					depend: 8,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Cyclone",					img: "yellow",	linked: [53, 60, 62],				depend: 8,		blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 0},
{name: "Discombobulate",			img: "red",		linked: [59],						depend: null,	blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 11},
{name: "Second Chance",				img: "red",		linked: [57, 64, 65],				depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 12},
{name: "Thunderclap",				img: "yellow",	linked: [59],						depend: 0,		blockedBy: null,	archetype: "Battle Monk",	cost: 2, archReq: 8},
{name: "Blood Pact",				img: "red",		linked: [58, 66, 67],				depend: null,	blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 10},
{name: "Martyr",					img: "yellow",	linked: [61],						depend: null,	blockedBy: null,	archetype: "Paladin",		cost: 2, archReq: 0},
{name: "Cheaper Uppercut",			img: "white",	linked: [61, 66],					depend: 7,		blockedBy: null,	archetype: null,			cost: 1, archReq: 0},
{name: "Brink of Madness",			img: "pink",	linked: [65, 67],					depend: null,	blockedBy: null,	archetype: null,			cost: 2, archReq: 0},
{name: "Haemorrhage",				img: "yellow",	linked: [63, 66],					depend: 63,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0},
{name: "Armor Breaker",				img: "pink",	linked: [45, 46],					depend: 25,		blockedBy: null,	archetype: "Fallen",		cost: 2, archReq: 0}
	],
	tree: [ // indentation funky so it's easier to fit on screen
[null,						null,							null,						null,								0,									null,								null,						null,							null],
[null,						null,							null,						null,								[[0], null, [1], null],				null,								null,						null,							null],
[null,						null,							2,							[null, [2], null, [1]],				1,									null,								null,						null,							null],
[null,						null,							null,						null,								[[1], null, [3], null],				null,								null,						null,							null],
[null,						null,							null,						null,								3,									null,								null,						null,							null],
[null,						null,							null,						null,								[[3], null, [4], null],				null,								null,						null,							null],
[[null, null, [10], [5]],	[null, [5], null, [10]],		10,							[null, [10], null, [4]],			4,									[null, [4], null, [6]],				6,							null,							null],
[5,							[null, [5], null, [7]],			[null, [5], [7], null],		null,								null,								null,								[[6], null, [8], null],		null,							null],
[[null, null, [11], [7]],	[null, [11], null, [7]],		7,							[null, [7], null, [9]],				9,									[null, [9], null, [8]],				8,							[null, [8], null, [14]],		[null, [8], [14], null]],
[[[7], null, [11], null],	null,							[[7], null, [12], null],	null,								[[9], null, [12, 13, 15], null],	null,								[[8], null, [13], null],	null,							[[8], null, [14], null]],
[11,						null,							12,							[null, [12], null, [9, 13, 15]],	[[9], [12], [15], [13]],			[null, [9, 12, 15], null, [13]],	13,							null,							14],
[[[11], null, [16], null],	null,							[[12], null, [17], null],	null,								15,									null,								[[13], null, [18], null],	null,							[[14], null, [19], null]],
[16,						[null, [16], [25], [17]],		17,							null,								[[15], null, [20], null],			null,								18,							[null, [18], [21], [19]],		19],
[null,						[[16, 17], null, [25], null],	null,						null,								20,									null,								null,						21,								null],
[null,						[[16, 17], null, [25], null],	null,						null,								[[20], null, [22], null],			null,								null,						[[21], null, [24], null],		null],
[null,						[[16, 17], null, [25], null],	23,							[null, [23], [27], [22]],			22,									null,								null,						24,								null],
[[null, null, [26], [25]],	25,								null,						[[22, 23], null, [27], null],		null,								null,								null,						[[24], null, [29], null],		null],
[26,						[null, [26], null, [27, 30]],	[null, [26], [30], [27]],	27,									[null, [27], null, [28]],			28,									[null, [28], [31], [29]],	29,								[null, [29], [33], null]],
[[[26], null, [32], null],	null,							30,							[[27], null, [35], null],			null,								null,								31,							null,							[[29], null, [33], null]],
[[[26], null, [32], null],	null,							null,						[[27], null, [35], null],			null,								null,								null,						null,							[[29], null, [33], null]],
[32,						null,							[null, null, [37], [35]],	35,									[null, [35], [38], [34]],			[null, [35, 38], null, [34]],		34,							[null, [34], null, [33]],		33],
[[[32], null, [36], null],	null,							[[35], null, [37], null],	null,								[[34, 35], null, [38], null],		null,								null,						null,							[[33], null, [40], null]],
[36,						[null, [36], [41], [37]],		37,							null,								38,									[null, [38], [43], [39]],			39,							[null, [39], [44], [40]],		40],
[[[36], null, [45], null],	41,								[[37], null, [42], null],	null,								[[38], null, [47], null],			43,									null,						44,								null],
[[[36], null, [45], null],	null,							42,							null,								[[38], null, [47], null],			null,								null,						[[44], null, [48], null],		null],
[[[36], null, [45], null],	null,							null,						null,								[[38], null, [47], null],			null,								null,						[[44], null, [48], null],		null],
[45,						[null, [45], [68], [46]],		46,							[null, [46], null, [47]],			47,									null,								[null, null, [49], [48]],	48,								[null, [48], [50], null]],
[[[45], null, [51], null],	68,								null,						null,								[[47], null, [53], null],			null,								49,							[null, [49], [57], [50]],		50],
[51,						[null, [51], [54], [52]],		52,							[null, [52], [55], [53]],			53,									[null, [53], [56], null],			null,						[[49, 50], null, [57], null],	null],
[[[51], null, [58], null],	54,								null,						55,									[[53], null, [59], null],			56,									[null, [56], null, [57]],	57,								null],
[[[51], null, [58], null],	null,							null,						null,								[[53], null, [59], null],			null,								null,						[[57], null, [61], null],		null],
[58,						null,							60,							[null, [60], null, [59]],			59,									[null, [59], [62], null],			null,						[[57], null, [61], null],		null],
[[[58], null, [63], null],	null,							null,						null,								null,								62,									[null, null, [65], [61]],	61,								[null, [61], [64], null]],
[63,						[null, [63], null, [66, 67]],	[null, [63], [67], [66]],	[null, [63, 67], null, [66]],		[null, [63, 67], [66], null],		null,								[[61], null, [65], null],	null,							[[61], null, [64], null]],
[null,						null,							67,							null,								66,									[null, [66], null, [65]],			65,							null,							64]
	],
	pages: [5, 9, 14, 19, 25, 30],
	archetypes: {"Fallen": {color: "#ff5555", icon: "3"}, "Battle Monk": {color: "#ffff55", icon: "2"}, "Paladin": {color: "#55ffff", icon: "0"}},
	chosen: [0],
	descriptions: [ // indentation funky so it's easier to fit on screen
"Violently bash the ground, dealing high<br/>damage in a large area<br/><br/>Mana Cost: 45<br/><br/>Total Damage: 150% (of DPS)<br/>- Neutral: 130%<br/>- Earth: 20%<br/><br/>AoE: 4 Blocks (circular)<br/>Range: 3 blocks",
"Improve your Main Attack's damage and<br/>range w/ spear<br/><br/>Main Attack Damage: +5%<br/>Main Attack Range: +1 Block",
"Reduce the Mana cost of Bash<br/><br/>Mana Cost: -10",
"Bash will hit a second time at a farther<br/>range<br/><br/>Total Damage: -50% (of DPS per bash)<br/>- Neutral: -50%<br/><br/>Range: +3 Blocks",
"Charge forward at high speed (hold shift while charging to cancel)<br/><br/>Mana Cost: 25",
"For every 1% or 1 Raw Main Attack<br/>Damage you have from items, gain +2%<br/>Walk Speed (Max 20%)<br/><br/>Damage Bonus: +5 (Raw)<br/><br/>Blocks:<br/>- Tougher Skin",
"Harden your skin and become<br/>permanently +5% more resistant<br/>For every 1% or 1 Raw Heath Regen you<br/>have from items, gain +10 Health (Max<br/>100)<br/><br/>Blocks:<br/>- Vehement",
"Rocket enemies in the air and deal massive damage<br/><br/>Mana Cost: 45<br/><br/>Total Damage: 280% (of DPS)<br/>- Neutral: 200%<br/>- Earth: 50%<br/>- Thunder: 50%<br/><br/>AoE: 1-3 Blocks (Cone-Shaped)<br/>Range: 5 Blocks",
"Emit a terrorizing roar that deals damage,<br/>pull nearby enemies, and add damage<br/>resistance to yourself and allies<br/><br/>Mana Cost: 35<br/><br/>Total Damage: 100% (of DPS)<br/>- Neutral: 50%<br/>- FIre: 50%<br/><br/>Effect: 10% Resistance Bonus to Allies<br/>Duration: 30s<br/><br/>AoE: 12 Blocks (circular)",
"Reduce the Mana cost of Charge<br/><br/>Mana Cost: -5",
"After using Charge, violently crash down<br/>into the ground and deal damage<br/><br/>Total Damage: 100% (of DPS)<br/>- Neutral: 100%<br/><br/>AoE: 4 Blocks",
"Increases base damage from all Earth<br/>attacks<br/><br/>Earth Damage: +2-4<br/>Earth Damage: +20%",
"Increases base damage from all Thunder<br/>attacks<br/><br/>Thunder Damage: +1-8<br/>Thunder Damage: +10%",
"Increases base damage from all Air<br/>attacks<br/><br/>Air Damage: +3-4<br/>Air Damage: +15%",
"Increases base damage from all Fire<br/>attacks<br/><br/>Fire Damage: +3-5<br/>Fire Damage: +15%",
"Increases base damage from all Water<br/>attacks<br/><br/>Water Damage: +2-4<br/>Water Damage: +15%",
"Bash will hit 4 times and trigger twice as<br/>fast<br/><br/>Total Damage: -20% (of DPS per bash)<br/>- Neutral: -20%<br/><br/>Range: +6 Blocks",
"Mobs hit by Uppercut will explode mid-air<br/>and receive additional damage<br/><br/>Total Damage: +100% (of DPS)<br/>- Neutral: +80%<br/>- Thunder: +20%",
"Damage enemies in your way when using<br/>Charge<br/><br/>Total Damage: 60%<br/>- Neutral: 20%<br/>- Air: 40%<br/><br/>AoE: 2 Blocks",
"Uppercut will light mobs on fire, dealing<br/>damage every 0.6 seconds<br/><br/>Total Damage: 50% (of DPS)<br/>- Fire: 50%<br/>Duration: 3s",
"Uppercut will deal a footsweep attack at a<br/>longer and wider angle. All elemental<br/>conversions become Water<br/><br/>Mana Cost: -10<br/><br/>Total Damage: -70% (of DPS)<br/>- Neutral: -70%<br/><br/>Range: +4 Blocks",
"War Scream deals more damage<br/><br/>Total Damage: +60% (of DPS)<br/>- Neutral: +30%<br/>- Air: +30%",
"When dodging a nearby enemy attack,<br/>get 30% chance to instantly attack back<br/><br/>Total Damage: 100% (of DPS)<br/>- Neutral: 60%<br/>- Air: 20%<br/>- Thunder: 20%",
"After casting 3 different spells in a row,<br/>your next spell will cost 5 mana",
"When casting War Scream, create a holy<br/>shield around you that reduces all<br/>incoming damage by 70% for 3 hits (20s<br/>cooldown)<br/>",
"After casting War Scream, become Corrupted (15s Cooldown). You cannot<br/>heal while in that state<br/>While Corrupted, every 2% of Health you<br/>lose will add +4 Raw Damage to your<br/>attacks (Max 120)",
"Improve your Main Attack's damage and<br/>range w/ spear<br/><br/>Main Attack Damage: +5%<br/>Range: +1 Block",
"Reduce the Mana Cost of Uppercut<br/>Mana Cost: -5",
"During Charge, you can steer and change<br/>direction",
"Mobs damaged by War Scream will target<br/>only you for at least 5s<br/>Reduce the Mana cost of War Scream<br/><br/>Mana Cost: -5",
"+30% Critical Hit Damage",
"War Scream will fire a projectile that can<br/>go through walls and deal damage multiple times<br/><br/>Total Damage: 25% (of DPS)<br/>- Neutral: 20%<br/>- Air: 5%",
"While Corriupted, every 1% of Health you<br/>lose will increase your damage by +3%<br/>(Max 300%)",
"If you receive a hit that's less than 5% of<br/>your max HP, gain 10 Mana (1s Cooldown)",
"Add +2 additional charges to Mantle of<br/>the Bovemists",
"When using Charge, mobs hit will halt<br/>your momentum and get knocked back<br/><br/>Total Damage: 150% (of DPS)<br/>- Neutral: 120%<br/>- Air: 20%<br/>- Water: 10%",
"Bash leaves a trail of boiling blood behind<br/>its first explosion, slowing down and<br/>damaging enemies above it every 0.4<br/>seconds<br/><br/>Total Damage: 30% (of DPS)<br/>- Neutral: 25%<br/>- Fire: 5%<br/><br/>Effect: 20% Slowness to Enemies",
"War Scream become deafening,<br/>increasing its range and giving damage<br/>bonus to players<br/><br/>Mana Cost: +10<br/><br/>Effect: 30% Damage Bonus to Players<br/>AoE: +2 Blocks",
"Increase your chance to attack with<br/>Counter by +30%",
"For every 100 Health Bonus you have<br/>from item IDs, gain +2% Fire Damage<br/>(Max 100%)",
"Increase the damage of Bash<br/><br/>Total Damage: +30% (of DPS)<br/>- Neutral: +30%",
"After leaving Corrupted, gain 2% of the<br/>health lost back for each enemy killed while Corrupted",
"After being hit by Fireworks, enemies will<br/>crash into the ground and receive more<br/>damage<br/><br/>Total Damage: +100% (of DPS)<br/>- Neutral: +80%<br/>- Earth: +20%",
"Mobs thrown into walls from Flying Kick<br/> will explode and receive additonal<br/>damage<br/><br/>Total Damage: 150% (of DPS)<br/>- Neutral: 100%<br/>- Fire: 50%<br/><br/>AoE: 4 Blocks",
"Regain back 30% of the damage you take<br/>as healing over 30s",
"Reduce the cooldown of Bak'al's Grasp<br/>by -5s, and increase the raw damage<br/>gained for every 2% of health lost by +1",
"For every 4% Reflection you have from<br/>items, gain +1/5s Mana Regen (Max<br/>10/5s)",
"Uppercut will create a strong gust of air,<br/>launching you upward with enemies (Hold<br/>shift to stay grounded)<br/><br/>Total Damage: +50% (of DPS)<br/>- Air: +50%<br/><br/>AoE: Circular Range: +2 Block",
"Gain +5% Base Resistance and become<br/>immune to knockback",
"When your Mantle of the Bovemist loses<br/>all charges, deal damage around you for<br/>each Mantle individually lost<br/><br/>Total Damage: 80% (of DPS, per mantle<br/>lost)<br/>- Neutral: 60%<br/>- Thunder: 20%<br/><br/>AoE: 5 Blocks (Circular)",
"Everytime you heal 5% of your max<br/>health, deal damage to all nearby<br/>enemies<br/><br/>Total Damage: 15% (of DPS)<br/>- Neutral: 10%<br/>- Thunder: +5%<br/><br/>AoE: 6 Blocks (Circular)",
"While Corrupted, every 3% Health you<br/>lose will add +1 AoE to Bash (Max 10)",
"War Scream will ripple the ground and<br/>deal damage 3 times in a large area<br/><br/>Total Damage: 50% (of DPS, per ripple)<br/>- Neutral: 30%<br/>- Earth: 10%<br/>- Air: 10%<br/><br/>AoE: 16 Blocks (Circular)",
"Reduce the Mana cost of Charge and<br/>increase your Walk Speed by +20%<br/><br/>Mana Cost: -5",
"While Corrupted, if your effective attack<br/>speed is Slow or lower, hitting an enemy<br/>with your Main Attack will add +1% to<br/>your Corrupted bar",
"Increase the damage of Uppercut, but<br/>also increase its mana cost<br/><br/>Mana cost: +10<br/><br/>Total Damage: +100% (of DPS)<br/>- Neutral: +100%",
"Bash will buff your allies' positive IDs.<br/>(15s Cooldown)<br/><br/>Effect: +20% ID Effectiveness to Allies Duration: 8s",
"Reduce the Mana cost of Bash<br/>Mana Cost: -5",
"Reduce the Mana cost of War Scream<br/>Mana Cost: -5",
"After casting War Scream, envelop<br/>yourself with a vortex that damages<br/>nearby enemies every 0.5s<br/><br/>Total Damage: 25% (of DPS)<br/>- Neutral: 10%<br/>- Air: 10%<br/>- Fire: 5%<br/><br/>Duration: 20s<br/>AoE: 4 Blocks (Circular)",
"Every time you hit an enemy, briefly<br/>increase your elemental damage dealt to<br/>them by +2 (Additive, Max +50). This<br/>bonus decays -5 every second",
"When you receive a fatal blow, survive<br/>and regain 30% of your Health (10m<br/>Cooldown)",
"Bash will cast at the player's position,<br/>gain additional AoE, and trigger twice as<br/>fast.<br/>All elemental conversions become<br/>Thunder<br/><br/>AoE: +3 Blocks (Circular)",
"If you do not have enough mana to cast a<br/>spell, spend health instead (0.6% health<br/>per mana)",
"When you receive a fatal blow, all nearby<br/>allies become invincible<br/><br/>Effect: 100% Invincibility to Allies<br/>Duration: 3s<br/>AoE: 12 Blocks (Circular)",
"Reduce the Mana cost of Uppercut<br/><br/>Mana Cost: -5",
"If your health is 25% full or less, gain<br/>+40% Resistance",
"Reduce Blood Pact's health cost. (0.3%<br/>health per mana)",
"While Corrupted, losing 30% Health will<br/>make your next Uppercut destroy<br/>enemies' defense, rendering them weaker<br/>to damage<br/><br/>Effect: -30% Resistance Bonus to<br/>Enemies<br/>Duration: 5s"
	]
}